[character]
success_symbol = "[>](bold blue)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"


[git_commit]
tag_symbol = " tag "

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "aws "

#[c]
#format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'
symbol = "cmake "


[cmd_duration]
format = '\[[â± $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'
symbol = "cobol "

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = "conda "

[crystal]
format = '\[[$symbol($version)]($style)\]'
symbol = "cr "

#[daml]
#format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = "dart"

[deno]
format = '\[[$symbol($version)]($style)\]'
symbol = "deno"

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = "docker"

[dotnet]
format = '\[[$symbol($version)(ðŸŽ¯ $tfm)]($style)\]'
symbol = ".NET"

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[golang]
format = '\[[$symbol($version)]($style)\]'

#[haskell]
#format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = "java"

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'
symbol = "kotlin"

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = "lua"

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = "nodejs"

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "pkg"

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = "perl"

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = "php"

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "py"

#[raku]
#format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'
symbol = "red"

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = "ruby"

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "rust"

[scala]
format = '\[[$symbol($version)]($style)\]'

#[spack]
#format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]\]'
symbol = "sudo"

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = "swift"

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
